controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# definir rutes sense utilitzar anotacions ( no recomanat )
inici:
    path: /
    controller: App\Controller\IniciController::inici