name: Deploy to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v4
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v4
      with:
        app-name: "wepapp-edgqe0eqazccerbu"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
